services:
  fastapi:
#    image: registry.diginfra.net/tsd/athenstest:latest
    image: vicding81/athenstest:latest
    container_name: fastapi
    hostname: fastapi
    volumes:
      - "./openapi/ver/current/sample_data:/app/data"
      - "./openapi/docker_build/app.py:/app/app.py"
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "8000:8000"

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - "8000:80"
#    volumes:
#      - "./openapi/ver:/usr/share/nginx/html:ro"

  prism_proxy:
    image: caddy
    container_name: prism_proxy
    hostname: prism_proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '8080:80'
    depends_on:
      - prism_current
#      - prism_2

  prism_current:
    image: stoplight/prism:4
    container_name: prism
    hostname: prism
    platform: "linux/amd64"
    init: true
    volumes:
      - "./openapi/ver/current/skg-if-openapi.yaml:/tmp/skg-if-api.yaml"
    command: ["proxy", "-h", "0.0.0.0", "/tmp/skg-if-api.yaml", "http://fastapi:8000", "--errors"]
    ports:
      - "4010:4010"

# Uncomment the following lines if you want to use the prism_current service
#  prism_current:
#    image: stoplight/prism:4
#    container_name: prism
#    hostname: prism
#    platform: "linux/amd64"
#    init: true
#    volumes:
#      - "./openapi/ver/current/skg-if-openapi.yaml:/tmp/skg-if-api.yaml"
#    command: ["proxy", "-h", "0.0.0.0", "/tmp/skg-if-api.yaml", "http://fastapi:8000", "--errors"]
#    ports:
#      - "4010:4010"
